spring:
  datasource:
    url: jdbc:postgresql://projetonuvem-1.cty28gs40kyf.us-east-1.rds.amazonaws.com/postgres
    username: postgres30
    password: projetonuvem3020
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect